version: 0.2

phases:
  install:
    commands:
      – echo Installing Mocha...
  build:
    commands:
      – serverless deploy –verbose

artifacts:
  files:
    – buildspec.yml
  discard-paths: yes
