version: 0.1

phases:
install:
commands:
– apt-get -y update
– apt-get -y install zip
– npm install -g serverless
build:
commands:
– serverless deploy –verbose

artifacts:
files:
– serverless.yml
discard-paths: yes
